// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>CD_Logon</b><br>
 * Generated     : <b>2025/01/07 9:54:14 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 11 amd64 10.0 <br>
 * 
 * @since  January 07, 2025
 * @author orest
 */
public abstract class CD_LogonHelper extends RationalTestScript
{
	/**
	 * ExistingCustomer: with default state.
	 *		text : Existing Customer
	 * 		.class : javax.swing.JRadioButton
	 * 		accessibleContext.accessibleName : Existing Customer
	 * 		name : radioButtonB
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject existingCustomer() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("existingCustomer"));
	}
	/**
	 * ExistingCustomer: with specific test context and state.
	 *		text : Existing Customer
	 * 		.class : javax.swing.JRadioButton
	 * 		accessibleContext.accessibleName : Existing Customer
	 * 		name : radioButtonB
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject existingCustomer(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("existingCustomer"), anchor, flags);
	}
	
	/**
	 * nameCombo: with default state.
	 *		.itemCount : 16
	 * 		.itemText : {Trent Culpito,Susan Flontly,Emma Trenchenza,Claire Stratus,Rick Tumbler,Tony Mi ...
	 * 		.class : javax.swing.JComboBox
	 * 		.priorLabel : Full Name:
	 * 		name : nameCombo
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject nameCombo() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("nameCombo"));
	}
	/**
	 * nameCombo: with specific test context and state.
	 *		.itemCount : 16
	 * 		.itemText : {Trent Culpito,Susan Flontly,Emma Trenchenza,Claire Stratus,Rick Tumbler,Tony Mi ...
	 * 		.class : javax.swing.JComboBox
	 * 		.priorLabel : Full Name:
	 * 		name : nameCombo
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject nameCombo(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("nameCombo"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName :   OK  
	 * 		name : ok-orderlogon
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName :   OK  
	 * 		name : ok-orderlogon
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point ExistingCustomer_state object in the SUT.
	 */
	protected IFtVerificationPoint ExistingCustomer_stateVP() 
	{
		return vp("ExistingCustomer_state");
	}
	protected IFtVerificationPoint ExistingCustomer_stateVP(TestObject anchor)
	{
		return vp("ExistingCustomer_state", anchor);
	}
	
	

	protected CD_LogonHelper()
	{
		setScriptName("CD_Logon");
	}
	
}

