// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>cics_terminal_inputs_3270</b><br>
 * Generated     : <b>2025/07/07 3:13:54 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 11 amd64 10.0 <br>
 * 
 * @since  July 07, 2025
 * @author orest
 */
public abstract class cics_terminal_inputs_3270Helper extends RationalTestScript
{
	/**
	 * Clear: with default state.
	 *		.class : com.ibm.eNetwork.HOD.common.gui.HButton
	 * 		accessibleContext.accessibleName : Clear
	 * 		.classIndex : 17
	 */
	protected GuiTestObject clear() 
	{
		return new GuiTestObject(
                        getMappedTestObject("clear"));
	}
	/**
	 * Clear: with specific test context and state.
	 *		.class : com.ibm.eNetwork.HOD.common.gui.HButton
	 * 		accessibleContext.accessibleName : Clear
	 * 		.classIndex : 17
	 */
	protected GuiTestObject clear(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("clear"), anchor, flags);
	}
	
	/**
	 * ConnectUsingTheCurrentConnectionProperties: with default state.
	 *		toolTipText : Connect Using the Current Connection Properties
	 * 		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : &Connect
	 * 		iconDescription : &Connect
	 * 		.classIndex : 4
	 */
	protected GuiTestObject connectUsingTheCurrentConnecti() 
	{
		return new GuiTestObject(
                        getMappedTestObject("connectUsingTheCurrentConnecti"));
	}
	/**
	 * ConnectUsingTheCurrentConnectionProperties: with specific test context and state.
	 *		toolTipText : Connect Using the Current Connection Properties
	 * 		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : &Connect
	 * 		iconDescription : &Connect
	 * 		.classIndex : 4
	 */
	protected GuiTestObject connectUsingTheCurrentConnecti(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("connectUsingTheCurrentConnecti"), anchor, flags);
	}
	
	/**
	 * DisconnectFromTheHost: with default state.
	 *		toolTipText : Disconnect from the Host
	 * 		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : &Disconnect
	 * 		iconDescription : &Disconnect
	 * 		.classIndex : 5
	 */
	protected GuiTestObject disconnectFromTheHost() 
	{
		return new GuiTestObject(
                        getMappedTestObject("disconnectFromTheHost"));
	}
	/**
	 * DisconnectFromTheHost: with specific test context and state.
	 *		toolTipText : Disconnect from the Host
	 * 		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : &Disconnect
	 * 		iconDescription : &Disconnect
	 * 		.classIndex : 5
	 */
	protected GuiTestObject disconnectFromTheHost(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("disconnectFromTheHost"), anchor, flags);
	}
	
	/**
	 * Field_13_51: with default state.
	 *		.startRow : 13
	 * 		.startCol : 51
	 * 		.text : Noaksey@beebhouse.com      
	 * 		.length : 27
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_13_51() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_13_51"));
	}
	/**
	 * Field_13_51: with specific test context and state.
	 *		.startRow : 13
	 * 		.startCol : 51
	 * 		.text : Noaksey@beebhouse.com      
	 * 		.length : 27
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_13_51(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_13_51"), anchor, flags);
	}
	
	/**
	 * Field_22_1: with default state.
	 *		.startRow : 22
	 * 		.startCol : 1
	 * 		.text :   Command ==> 
	 * 		.length : 14
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_22_1() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_22_1"));
	}
	/**
	 * Field_22_1: with specific test context and state.
	 *		.startRow : 22
	 * 		.startCol : 1
	 * 		.text :   Command ==> 
	 * 		.length : 14
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_22_1(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_22_1"), anchor, flags);
	}
	
	/**
	 * Host: with default state.
	 *		.class : com.ibm.terminal.tester.gui.misc.AccessibleTextField
	 * 		.priorLabel : Host:
	 * 		accessibleContext.accessibleName : Host:
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject host() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("host"));
	}
	/**
	 * Host: with specific test context and state.
	 *		.class : com.ibm.terminal.tester.gui.misc.AccessibleTextField
	 * 		.priorLabel : Host:
	 * 		accessibleContext.accessibleName : Host:
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject host(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("host"), anchor, flags);
	}
	
	/**
	 * IBMExtensionForTerminalBasedApplications: with default state.
	 *		.captionText : IBM Extension for Terminal-based Applications
	 * 		accessibleContext.accessibleRole : frame
	 * 		.class : com.ibm.terminal.tester.gui.panel.TFrame
	 * 		accessibleContext.accessibleName : IBM Extension for Terminal-based Applications
	 */
	protected FTETopLevelTestObject ibmExtensionForTerminalBasedAp() 
	{
		return new FTETopLevelTestObject(
                        getMappedTestObject("ibmExtensionForTerminalBasedAp"));
	}
	/**
	 * IBMExtensionForTerminalBasedApplications: with specific test context and state.
	 *		.captionText : IBM Extension for Terminal-based Applications
	 * 		accessibleContext.accessibleRole : frame
	 * 		.class : com.ibm.terminal.tester.gui.panel.TFrame
	 * 		accessibleContext.accessibleName : IBM Extension for Terminal-based Applications
	 */
	protected FTETopLevelTestObject ibmExtensionForTerminalBasedAp(TestObject anchor, long flags) 
	{
		return new FTETopLevelTestObject(
                        getMappedTestObject("ibmExtensionForTerminalBasedAp"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point email object in the SUT.
	 */
	protected IFtVerificationPoint emailVP() 
	{
		return vp("email");
	}
	protected IFtVerificationPoint emailVP(TestObject anchor)
	{
		return vp("email", anchor);
	}
	
	

	protected cics_terminal_inputs_3270Helper()
	{
		setScriptName("cics_terminal_inputs_3270");
	}
	
}

