// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>DataDriven_3270</b><br>
 * Generated     : <b>2025/07/07 3:17:29 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 11 amd64 10.0 <br>
 * 
 * @since  July 07, 2025
 * @author orest
 */
public abstract class DataDriven_3270Helper extends RationalTestScript
{
	/**
	 * Field_22_25: with default state.
	 *		.startRow : 22
	 * 		.startCol : 25
	 * 		.text : 1
	 * 		.length : 1
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject Code() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Code"));
	}
	/**
	 * Field_22_25: with specific test context and state.
	 *		.startRow : 22
	 * 		.startCol : 25
	 * 		.text : 1
	 * 		.length : 1
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject Code(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Code"), anchor, flags);
	}
	
	/**
	 * Field_4_51: with default state.
	 *		.startRow : 4
	 * 		.startCol : 51
	 * 		.text : 0000000000
	 * 		.length : 10
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject CustNum() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("CustNum"));
	}
	/**
	 * Field_4_51: with specific test context and state.
	 *		.startRow : 4
	 * 		.startCol : 51
	 * 		.text : 0000000000
	 * 		.length : 10
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject CustNum(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("CustNum"), anchor, flags);
	}
	
	/**
	 * Field_4_51: with default state.
	 *		.startRow : 4
	 * 		.startCol : 51
	 * 		.text : 0000000001
	 * 		.length : 10
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject CustomerNumber() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("CustomerNumber"));
	}
	/**
	 * Field_4_51: with specific test context and state.
	 *		.startRow : 4
	 * 		.startCol : 51
	 * 		.text : 0000000001
	 * 		.length : 10
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject CustomerNumber(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("CustomerNumber"), anchor, flags);
	}
	
	/**
	 * Field_7_51: with default state.
	 *		.startRow : 7
	 * 		.startCol : 51
	 * 		.text : 1950-07-11
	 * 		.length : 10
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject DOB() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("DOB"));
	}
	/**
	 * Field_7_51: with specific test context and state.
	 *		.startRow : 7
	 * 		.startCol : 51
	 * 		.text : 1950-07-11
	 * 		.length : 10
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject DOB(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("DOB"), anchor, flags);
	}
	
	/**
	 * Field_13_51: with default state.
	 *		.startRow : 13
	 * 		.startCol : 51
	 * 		.text : A.Pandy@beebhouse.com      
	 * 		.length : 27
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject Email() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Email"));
	}
	/**
	 * Field_13_51: with specific test context and state.
	 *		.startRow : 13
	 * 		.startCol : 51
	 * 		.text : A.Pandy@beebhouse.com      
	 * 		.length : 27
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject Email(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Email"), anchor, flags);
	}
	
	/**
	 * Field_5_51: with default state.
	 *		.startRow : 5
	 * 		.startCol : 51
	 * 		.text : Andrew    
	 * 		.length : 10
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject FirstName() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("FirstName"));
	}
	/**
	 * Field_5_51: with specific test context and state.
	 *		.startRow : 5
	 * 		.startCol : 51
	 * 		.text : Andrew    
	 * 		.length : 10
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject FirstName(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("FirstName"), anchor, flags);
	}
	
	/**
	 * Field_8_51: with default state.
	 *		.startRow : 8
	 * 		.startCol : 51
	 * 		.text :                     
	 * 		.length : 20
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject HouseName() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("HouseName"));
	}
	/**
	 * Field_8_51: with specific test context and state.
	 *		.startRow : 8
	 * 		.startCol : 51
	 * 		.text :                     
	 * 		.length : 20
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject HouseName(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("HouseName"), anchor, flags);
	}
	
	/**
	 * Field_9_51: with default state.
	 *		.startRow : 9
	 * 		.startCol : 51
	 * 		.text : 34  
	 * 		.length : 4
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject HouseNumber() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("HouseNumber"));
	}
	/**
	 * Field_9_51: with specific test context and state.
	 *		.startRow : 9
	 * 		.startCol : 51
	 * 		.text : 34  
	 * 		.length : 4
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject HouseNumber(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("HouseNumber"), anchor, flags);
	}
	
	/**
	 * Field_6_51: with default state.
	 *		.startRow : 6
	 * 		.startCol : 51
	 * 		.text : Pandy               
	 * 		.length : 20
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject LastName() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("LastName"));
	}
	/**
	 * Field_6_51: with specific test context and state.
	 *		.startRow : 6
	 * 		.startCol : 51
	 * 		.text : Pandy               
	 * 		.length : 20
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject LastName(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("LastName"), anchor, flags);
	}
	
	/**
	 * Field_12_51: with default state.
	 *		.startRow : 12
	 * 		.startCol : 51
	 * 		.text : 07799 123456        
	 * 		.length : 20
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject Mobile() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Mobile"));
	}
	/**
	 * Field_12_51: with specific test context and state.
	 *		.startRow : 12
	 * 		.startCol : 51
	 * 		.text : 07799 123456        
	 * 		.length : 20
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject Mobile(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Mobile"), anchor, flags);
	}
	
	/**
	 * Field_10_51: with default state.
	 *		.startRow : 10
	 * 		.startCol : 51
	 * 		.text : PI101OO 
	 * 		.length : 8
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject Postcode() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Postcode"));
	}
	/**
	 * Field_10_51: with specific test context and state.
	 *		.startRow : 10
	 * 		.startCol : 51
	 * 		.text : PI101OO 
	 * 		.length : 8
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject Postcode(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Postcode"), anchor, flags);
	}
	
	/**
	 * Field_11_51: with default state.
	 *		.startRow : 11
	 * 		.startCol : 51
	 * 		.text : 01962 811234        
	 * 		.length : 20
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject Telephone() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Telephone"));
	}
	/**
	 * Field_11_51: with specific test context and state.
	 *		.startRow : 11
	 * 		.startCol : 51
	 * 		.text : 01962 811234        
	 * 		.length : 20
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject Telephone(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Telephone"), anchor, flags);
	}
	
	/**
	 * Clear: with default state.
	 *		.class : com.ibm.eNetwork.HOD.common.gui.HButton
	 * 		accessibleContext.accessibleName : Clear
	 * 		.classIndex : 17
	 */
	protected GuiTestObject clear() 
	{
		return new GuiTestObject(
                        getMappedTestObject("clear"));
	}
	/**
	 * Clear: with specific test context and state.
	 *		.class : com.ibm.eNetwork.HOD.common.gui.HButton
	 * 		accessibleContext.accessibleName : Clear
	 * 		.classIndex : 17
	 */
	protected GuiTestObject clear(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("clear"), anchor, flags);
	}
	
	/**
	 * ConnectUsingTheCurrentConnectionProperties: with default state.
	 *		toolTipText : Connect Using the Current Connection Properties
	 * 		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : &Connect
	 * 		iconDescription : &Connect
	 * 		.classIndex : 4
	 */
	protected GuiTestObject connectUsingTheCurrentConnecti() 
	{
		return new GuiTestObject(
                        getMappedTestObject("connectUsingTheCurrentConnecti"));
	}
	/**
	 * ConnectUsingTheCurrentConnectionProperties: with specific test context and state.
	 *		toolTipText : Connect Using the Current Connection Properties
	 * 		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : &Connect
	 * 		iconDescription : &Connect
	 * 		.classIndex : 4
	 */
	protected GuiTestObject connectUsingTheCurrentConnecti(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("connectUsingTheCurrentConnecti"), anchor, flags);
	}
	
	/**
	 * DisconnectFromTheHost: with default state.
	 *		toolTipText : Disconnect from the Host
	 * 		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : &Disconnect
	 * 		iconDescription : &Disconnect
	 * 		.classIndex : 5
	 */
	protected GuiTestObject disconnectFromTheHost() 
	{
		return new GuiTestObject(
                        getMappedTestObject("disconnectFromTheHost"));
	}
	/**
	 * DisconnectFromTheHost: with specific test context and state.
	 *		toolTipText : Disconnect from the Host
	 * 		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : &Disconnect
	 * 		iconDescription : &Disconnect
	 * 		.classIndex : 5
	 */
	protected GuiTestObject disconnectFromTheHost(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("disconnectFromTheHost"), anchor, flags);
	}
	
	/**
	 * Field_1_13: with default state.
	 *		.startRow : 1
	 * 		.startCol : 13
	 * 		.text : General Insurance Customer Menu                                                  ...
	 * 		.length : 235
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_1_13() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_1_13"));
	}
	/**
	 * Field_1_13: with specific test context and state.
	 *		.startRow : 1
	 * 		.startCol : 13
	 * 		.text : General Insurance Customer Menu                                                  ...
	 * 		.length : 235
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_1_13(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_1_13"), anchor, flags);
	}
	
	/**
	 * Field_1_2: with default state.
	 *		.startRow : 1
	 * 		.startCol : 2
	 * 		.text : WELCOME TO CICS 09:37:26                                                         ...
	 * 		.length : 1919
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_1_2() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_1_2"));
	}
	/**
	 * Field_1_2: with specific test context and state.
	 *		.startRow : 1
	 * 		.startCol : 2
	 * 		.text : WELCOME TO CICS 09:37:26                                                         ...
	 * 		.length : 1919
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_1_2(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_1_2"), anchor, flags);
	}
	
	/**
	 * Field_1_2: with default state.
	 *		.startRow : 1
	 * 		.startCol : 2
	 * 		.text : RegularExpression(WELCOME TO CICS TS V5R6\. CICS REGION - CIC56M11 \d\d:\d\d:\d\ ...
	 * 		.length : 1759
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_1_2_2() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_1_2_2"));
	}
	/**
	 * Field_1_2: with specific test context and state.
	 *		.startRow : 1
	 * 		.startCol : 2
	 * 		.text : RegularExpression(WELCOME TO CICS TS V5R6\. CICS REGION - CIC56M11 \d\d:\d\d:\d\ ...
	 * 		.length : 1759
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_1_2_2(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_1_2_2"), anchor, flags);
	}
	
	/**
	 * Field_1_55: with default state.
	 *		.startRow : 1
	 * 		.startCol : 55
	 * 		.text : SCREEN  IY3ITC93/         
	 * 		.length : 26
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_1_55() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_1_55"));
	}
	/**
	 * Field_1_55: with specific test context and state.
	 *		.startRow : 1
	 * 		.startCol : 55
	 * 		.text : SCREEN  IY3ITC93/         
	 * 		.length : 26
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_1_55(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_1_55"), anchor, flags);
	}
	
	/**
	 * Field_22_16: with default state.
	 *		.startRow : 22
	 * 		.startCol : 16
	 * 		.text :                                                                                  ...
	 * 		.length : 225
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_22_16() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_22_16"));
	}
	/**
	 * Field_22_16: with specific test context and state.
	 *		.startRow : 22
	 * 		.startCol : 16
	 * 		.text :                                                                                  ...
	 * 		.length : 225
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_22_16(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_22_16"), anchor, flags);
	}
	
	/**
	 * Field_24_5: with default state.
	 *		.startRow : 24
	 * 		.startCol : 5
	 * 		.text :                                                                             
	 * 		.length : 76
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_24_5() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_24_5"));
	}
	/**
	 * Field_24_5: with specific test context and state.
	 *		.startRow : 24
	 * 		.startCol : 5
	 * 		.text :                                                                             
	 * 		.length : 76
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_24_5(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_24_5"), anchor, flags);
	}
	
	/**
	 * Field_5_51: with default state.
	 *		.startRow : 5
	 * 		.startCol : 51
	 * 		.text :           
	 * 		.length : 10
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_5_51() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_5_51"));
	}
	/**
	 * Field_5_51: with specific test context and state.
	 *		.startRow : 5
	 * 		.startCol : 51
	 * 		.text :           
	 * 		.length : 10
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_5_51(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_5_51"), anchor, flags);
	}
	
	/**
	 * Field_6_51: with default state.
	 *		.startRow : 6
	 * 		.startCol : 51
	 * 		.text :                     
	 * 		.length : 20
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_6_51() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_6_51"));
	}
	/**
	 * Field_6_51: with specific test context and state.
	 *		.startRow : 6
	 * 		.startCol : 51
	 * 		.text :                     
	 * 		.length : 20
	 * 		.class : com.ibm.eNetwork.ECL.ECLField
	 */
	protected TextGuiTestObject field_6_51(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("field_6_51"), anchor, flags);
	}
	
	/**
	 * Host: with default state.
	 *		.class : com.ibm.terminal.tester.gui.misc.AccessibleTextField
	 * 		.priorLabel : Host:
	 * 		accessibleContext.accessibleName : Host:
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject host() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("host"));
	}
	/**
	 * Host: with specific test context and state.
	 *		.class : com.ibm.terminal.tester.gui.misc.AccessibleTextField
	 * 		.priorLabel : Host:
	 * 		accessibleContext.accessibleName : Host:
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject host(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("host"), anchor, flags);
	}
	
	/**
	 * IBMExtensionForTerminalBasedApplications: with default state.
	 *		.captionText : IBM Extension for Terminal-based Applications
	 * 		accessibleContext.accessibleRole : frame
	 * 		.class : com.ibm.terminal.tester.gui.panel.TFrame
	 * 		accessibleContext.accessibleName : IBM Extension for Terminal-based Applications
	 */
	protected FTETopLevelTestObject ibmExtensionForTerminalBasedAp() 
	{
		return new FTETopLevelTestObject(
                        getMappedTestObject("ibmExtensionForTerminalBasedAp"));
	}
	/**
	 * IBMExtensionForTerminalBasedApplications: with specific test context and state.
	 *		.captionText : IBM Extension for Terminal-based Applications
	 * 		accessibleContext.accessibleRole : frame
	 * 		.class : com.ibm.terminal.tester.gui.panel.TFrame
	 * 		accessibleContext.accessibleName : IBM Extension for Terminal-based Applications
	 */
	protected FTETopLevelTestObject ibmExtensionForTerminalBasedAp(TestObject anchor, long flags) 
	{
		return new FTETopLevelTestObject(
                        getMappedTestObject("ibmExtensionForTerminalBasedAp"), anchor, flags);
	}
	
	/**
	 * TerminalOIA: with default state.
	 *		.class : com.ibm.eNetwork.ECL.ECLOIA
	 * 		.testObjectState : DISABLED
	 */
	protected GuiTestObject terminalOIA() 
	{
		return new GuiTestObject(
                        getMappedTestObject("terminalOIA"));
	}
	/**
	 * TerminalOIA: with specific test context and state.
	 *		.class : com.ibm.eNetwork.ECL.ECLOIA
	 * 		.testObjectState : DISABLED
	 */
	protected GuiTestObject terminalOIA(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("terminalOIA"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point DOB object in the SUT.
	 */
	protected IFtVerificationPoint DOBVP() 
	{
		return vp("DOB");
	}
	protected IFtVerificationPoint DOBVP(TestObject anchor)
	{
		return vp("DOB", anchor);
	}
	
	/**
	 * Locate and return the verification point Email object in the SUT.
	 */
	protected IFtVerificationPoint EmailVP() 
	{
		return vp("Email");
	}
	protected IFtVerificationPoint EmailVP(TestObject anchor)
	{
		return vp("Email", anchor);
	}
	
	/**
	 * Locate and return the verification point FirstName object in the SUT.
	 */
	protected IFtVerificationPoint FirstNameVP() 
	{
		return vp("FirstName");
	}
	protected IFtVerificationPoint FirstNameVP(TestObject anchor)
	{
		return vp("FirstName", anchor);
	}
	
	/**
	 * Locate and return the verification point HouseName object in the SUT.
	 */
	protected IFtVerificationPoint HouseNameVP() 
	{
		return vp("HouseName");
	}
	protected IFtVerificationPoint HouseNameVP(TestObject anchor)
	{
		return vp("HouseName", anchor);
	}
	
	/**
	 * Locate and return the verification point HouseNumber object in the SUT.
	 */
	protected IFtVerificationPoint HouseNumberVP() 
	{
		return vp("HouseNumber");
	}
	protected IFtVerificationPoint HouseNumberVP(TestObject anchor)
	{
		return vp("HouseNumber", anchor);
	}
	
	/**
	 * Locate and return the verification point LastName object in the SUT.
	 */
	protected IFtVerificationPoint LastNameVP() 
	{
		return vp("LastName");
	}
	protected IFtVerificationPoint LastNameVP(TestObject anchor)
	{
		return vp("LastName", anchor);
	}
	
	/**
	 * Locate and return the verification point Mobile object in the SUT.
	 */
	protected IFtVerificationPoint MobileVP() 
	{
		return vp("Mobile");
	}
	protected IFtVerificationPoint MobileVP(TestObject anchor)
	{
		return vp("Mobile", anchor);
	}
	
	/**
	 * Locate and return the verification point Postcode object in the SUT.
	 */
	protected IFtVerificationPoint PostcodeVP() 
	{
		return vp("Postcode");
	}
	protected IFtVerificationPoint PostcodeVP(TestObject anchor)
	{
		return vp("Postcode", anchor);
	}
	
	/**
	 * Locate and return the verification point Telephone object in the SUT.
	 */
	protected IFtVerificationPoint TelephoneVP() 
	{
		return vp("Telephone");
	}
	protected IFtVerificationPoint TelephoneVP(TestObject anchor)
	{
		return vp("Telephone", anchor);
	}
	
	

	protected DataDriven_3270Helper()
	{
		setScriptName("DataDriven_3270");
	}
	
}

