// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>DevOpsAPI</b><br>
 * Generated     : <b>2025/02/14 10:24:13 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 11 amd64 10.0 <br>
 * 
 * @since  February 14, 2025
 * @author orest
 */
public abstract class DevOpsAPIHelper extends RationalTestScript
{
	/**
	 * DevOpsTestIntegrationsAndAPIs: with default state.
	 *		.text : DevOps Test Integrations and APIs
	 * 		.class : SunAwtFrame
	 * 		.processName : IntegrationTester.exe
	 * 		.name : DevOps Test Integrations and APIs
	 */
	protected TopLevelSubitemTestObject devOpsTestIntegrationsAndAPIsw() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("devOpsTestIntegrationsAndAPIsw"));
	}
	/**
	 * DevOpsTestIntegrationsAndAPIs: with specific test context and state.
	 *		.text : DevOps Test Integrations and APIs
	 * 		.class : SunAwtFrame
	 * 		.processName : IntegrationTester.exe
	 * 		.name : DevOps Test Integrations and APIs
	 */
	protected TopLevelSubitemTestObject devOpsTestIntegrationsAndAPIsw(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("devOpsTestIntegrationsAndAPIsw"), anchor, flags);
	}
	
	

	protected DevOpsAPIHelper()
	{
		setScriptName("DevOpsAPI");
	}
	
}

