// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Pdf_Test</b><br>
 * Generated     : <b>2024/11/25 2:43:17 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 11 amd64 10.0 <br>
 * 
 * @since  November 25, 2024
 * @author orest
 */
public abstract class Pdf_TestHelper extends RationalTestScript
{
	/**
	 * AVPageView: with default state.
	 *		.text : AVPageView
	 * 		.class : AVL_AVView
	 * 		.name : AVPageView
	 * 		.classIndex : 4
	 */
	protected GuiSubitemTestObject avPageViewwindow() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("avPageViewwindow"));
	}
	/**
	 * AVPageView: with specific test context and state.
	 *		.text : AVPageView
	 * 		.class : AVL_AVView
	 * 		.name : AVPageView
	 * 		.classIndex : 4
	 */
	protected GuiSubitemTestObject avPageViewwindow(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("avPageViewwindow"), anchor, flags);
	}
	
	/**
	 * AVUITopRightCommandCluster: with default state.
	 *		.text : AVUITopRightCommandCluster
	 * 		.class : AVL_AVView
	 * 		.name : AVUITopRightCommandCluster
	 * 		.classIndex : 2
	 */
	protected GuiSubitemTestObject avuiTopRightCommandClusterwind() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("avuiTopRightCommandClusterwind"));
	}
	/**
	 * AVUITopRightCommandCluster: with specific test context and state.
	 *		.text : AVUITopRightCommandCluster
	 * 		.class : AVL_AVView
	 * 		.name : AVUITopRightCommandCluster
	 * 		.classIndex : 2
	 */
	protected GuiSubitemTestObject avuiTopRightCommandClusterwind(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("avuiTopRightCommandClusterwind"), anchor, flags);
	}
	
	/**
	 * Context: with default state.
	 *		.text : Context
	 * 		.class : .Menupopup
	 * 		.name : Context
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject contextpopupMenu() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("contextpopupMenu"));
	}
	/**
	 * Context: with specific test context and state.
	 *		.text : Context
	 * 		.class : .Menupopup
	 * 		.name : Context
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject contextpopupMenu(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("contextpopupMenu"), anchor, flags);
	}
	
	/**
	 * ItemsView: with default state.
	 *		.class : .List
	 * 		.name : Items View
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject itemsViewlist() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("itemsViewlist"));
	}
	/**
	 * ItemsView: with specific test context and state.
	 *		.class : .List
	 * 		.name : Items View
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject itemsViewlist(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("itemsViewlist"), anchor, flags);
	}
	
	/**
	 * Name: with default state.
	 *		.class : .Text
	 * 		.name : Name
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject nametext() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("nametext"));
	}
	/**
	 * Name: with specific test context and state.
	 *		.class : .Text
	 * 		.name : Name
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject nametext(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("nametext"), anchor, flags);
	}
	
	/**
	 * NavigationPane: with default state.
	 *		.text : null
	 * 		.class : SysTreeView32
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject navigationPanetree() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("navigationPanetree"));
	}
	/**
	 * NavigationPane: with specific test context and state.
	 *		.text : null
	 * 		.class : SysTreeView32
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject navigationPanetree(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("navigationPanetree"), anchor, flags);
	}
	
	/**
	 * PageUp: with default state.
	 *		.text : Page up
	 * 		.class : .Pushbutton
	 * 		.name : Page up
	 * 		.classIndex : 1
	 */
	protected GuiTestObject pageUpbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("pageUpbutton"));
	}
	/**
	 * PageUp: with specific test context and state.
	 *		.text : Page up
	 * 		.class : .Pushbutton
	 * 		.name : Page up
	 * 		.classIndex : 1
	 */
	protected GuiTestObject pageUpbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("pageUpbutton"), anchor, flags);
	}
	
	

	protected Pdf_TestHelper()
	{
		setScriptName("Pdf_Test");
	}
	
}

